# Authentication settings
auth:
  enabled: true
  rootPassword: password
  username: root
  password: password
  database: my_db

# Persistent storage settings
persistence:
  enabled: true
  size: 5Gi

# Disable replica set
replicaSet:
  enabled: false

service:
  type: ClusterIP
  ports:
    mongodb: 27017