apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-producer
  labels:
    app: my-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-producer
  template:
    metadata:
      labels:
        app: my-producer
    spec:
      containers:
        - name: my-producer
          image: ghcr.io/jotace-labs/my-producer:a08310a 
          imagePullPolicy: IfNotPresent
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "50m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "200m"
          env:
            - name: KAFKA_BROKERS
              value: "redpanda.default.svc.cluster.local:9092"
